language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"

branches:
  only:
    - master

install:
  - # TODO: this is temporary, remove it when django-freeradius 0.1 is released
  - pip install https://github.com/openwisp/django-freeradius/tarball/master
  - pip install $DJANGO
  - python setup.py -q develop
  - pip install -r requirements-test.txt

before_script:
  - |
      openwisp-utils-qa-checks \
        --migration-path "./openwisp_radius/migrations" \
        --migration-module openwisp_radius
  - mkdir tests/media

script:
  - coverage run --source=openwisp_radius runtests.py

after_success:
  coveralls
